version: '3.1'
networks:
  default:
    external:
      name: embers-net
services:
  redis:
    image: redis:latest
    ports:
      - "6379"
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      - "POSTGRES_USER=cityofbrass"
      - "POSTGRES_PASSWORD=cityofbrass"
