
default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: cityofbrass
  password: cityofbrass
  pool: 5
  host: <%= ENV['DOCKER_POSTGRES_HOST'] %>
  port: <%= ENV['DOCKER_POSTGRES_PORT'] %>

development:
  <<: *default
  database: cityofbrass_development

test:
  <<: *default
  database: cityofbrass_test

production:
  <<: *default
  database: cityofbrass_production
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
